stack: cedar
processes_owner: web
project:
  base_path: /opt/apps
  base_domain: lvh.me
dirs:
  app: _app
  cache: _cache
  env: _env
buildpacks:
  path: /opt/buildpacks
  order:
    - ruby
    - nodejs
    - clojure
    - python
    - java
    - gradle
    - grails
    - scala
    - play
    - php
nginx:
  configs_path: /etc/nginx/apps
  ssl_certs_and_keys_path: /etc/nginx/apps/ssl
supervisord:
  configs_path: /etc/supervisor/conf.d
ports:
  path: /var/run/ports
  secure_following: 5
